"""The garment library behind Discover My Style.

Static, version-controlled styling knowledge. No AI call, no network, no cost.

Two rules this file follows deliberately:

- Indian and global garments sit in one library, not two. A user in Mumbai may
  live in jeans and a user in Toronto may wear a saree every week; neither is
  the default for the other. Region tags describe a garment's tradition, never
  a prediction about the person looking at it.
- `suits_shapes` orders results. It never hides a garment. Body shape changes
  which explanation is shown first, not what a person is allowed to wear.
"""
from __future__ import annotations

from dataclasses import dataclass, field

REGIONS = ("indian", "global", "both")
FORMALITY = ("casual", "smart_casual", "business", "formal", "occasion")
CLIMATES = ("hot", "warm", "temperate", "cold", "humid", "any")

CATEGORIES = (
    "tops", "shirts", "trousers", "jeans", "skirts", "dresses", "jackets",
    "blazers", "outerwear", "sets", "traditional", "footwear", "bags",
    "accessories",
)

BODY_TYPES = (
    "pear", "apple", "hourglass", "rectangle", "inverted_triangle",
    "unsure", "uncategorised",
)


@dataclass(frozen=True)
class Garment:
    key: str
    name: str
    category: str
    region: str
    description: str
    silhouette: str
    fit: str
    formality: str
    occasions: list[str]
    climates: list[str]
    styling: list[str]
    # Ordering only. An empty list means it suits broadly.
    suits_shapes: list[str] = field(default_factory=list)
    # A colour role from the season palettes: best | neutrals | accents.
    colour_role: str = "best"
    aesthetics: list[str] = field(default_factory=list)
    note: str = ""


def _g(**kwargs) -> Garment:
    return Garment(**kwargs)


# ------------------------------------------------------- Indian & South Asian

INDIAN: list[Garment] = [
    _g(key="saree_silk", name="Silk saree", category="traditional", region="indian",
       description="Six to nine yards of silk, draped and pleated at the waist.",
       silhouette="draped", fit="adjustable", formality="occasion",
       occasions=["wedding", "festival", "formal"], climates=["warm", "temperate", "humid"],
       styling=["The drape is adjustable, so it fits every body without alteration",
                "A contrast blouse changes the whole outfit without a new saree",
                "Pleat width changes how much volume sits at the front"],
       suits_shapes=[], aesthetics=["Traditional", "Elegant"],
       note="Kanjeevaram, Banarasi and Paithani are regional weaves, not separate garments."),
    _g(key="saree_cotton", name="Cotton saree", category="traditional", region="indian",
       description="A lighter everyday drape in cotton or cotton blend.",
       silhouette="draped", fit="adjustable", formality="smart_casual",
       occasions=["everyday", "work", "festival"], climates=["hot", "humid", "warm"],
       styling=["Breathes in heat where silk does not",
                "Starched cotton holds a crisper pleat",
                "Works with a plain blouse and flat sandals for daily wear"],
       aesthetics=["Traditional", "Minimalist"]),
    _g(key="saree_georgette", name="Georgette saree", category="traditional", region="indian",
       description="A fluid drape that falls close to the body.",
       silhouette="draped", fit="fluid", formality="occasion",
       occasions=["evening", "wedding", "party"], climates=["temperate", "warm"],
       styling=["Falls rather than stands, so pleats stay narrow",
                "Suits a seamless drape more than a heavily pleated one"],
       suits_shapes=["rectangle", "inverted_triangle"], aesthetics=["Contemporary", "Elegant"]),
    _g(key="lehenga_aline", name="A-line lehenga", category="traditional", region="indian",
       description="A flared skirt widening gently from the waist, with a blouse and dupatta.",
       silhouette="a_line", fit="fitted_waist", formality="occasion",
       occasions=["wedding", "festival"], climates=["temperate", "warm"],
       styling=["The flare starts at the waist, which balances wider hips",
                "A dupatta over one shoulder adds a vertical line",
                "Blouse length changes how much waist shows — entirely your call"],
       suits_shapes=["pear", "apple", "rectangle"], aesthetics=["Traditional", "Romantic"]),
    _g(key="lehenga_mermaid", name="Mermaid lehenga", category="traditional", region="indian",
       description="Fitted to below the knee, then flared.",
       silhouette="fit_and_flare", fit="fitted", formality="occasion",
       occasions=["wedding"], climates=["temperate"],
       styling=["Follows the waist and hip line closely",
                "The flare point can be raised or lowered by your tailor"],
       suits_shapes=["hourglass", "rectangle"], aesthetics=["Elegant", "Contemporary"]),
    _g(key="lehenga_panelled", name="Panelled lehenga", category="traditional", region="indian",
       description="Vertical panels creating volume that falls from the waist.",
       silhouette="flared", fit="fitted_waist", formality="occasion",
       occasions=["wedding", "festival"], climates=["temperate", "cold"],
       styling=["Panels read as vertical lines even at full volume",
                "Heavier fabrics hold the shape without a stiff underskirt"],
       suits_shapes=["rectangle", "apple"], aesthetics=["Traditional"]),
    _g(key="anarkali", name="Anarkali", category="traditional", region="indian",
       description="A fitted bodice flaring into a long, full skirt.",
       silhouette="fit_and_flare", fit="fitted_bodice", formality="occasion",
       occasions=["wedding", "festival", "formal"], climates=["warm", "temperate"],
       styling=["The flare begins high, so it skims rather than follows the hip",
                "Floor length lengthens the whole line",
                "Churidar or straight trousers underneath both work"],
       suits_shapes=["pear", "apple", "rectangle"], aesthetics=["Traditional", "Romantic"]),
    _g(key="kurta_straight", name="Straight kurta", category="traditional", region="indian",
       description="A straight-cut tunic, knee length or longer.",
       silhouette="straight", fit="relaxed", formality="smart_casual",
       occasions=["everyday", "work", "festival"], climates=["hot", "warm", "humid"],
       styling=["The most versatile piece in this library — trousers, jeans or churidar",
                "Side slits change how much it moves",
                "A belt over it defines a waist, if you want one"],
       suits_shapes=["hourglass", "inverted_triangle", "apple"],
       aesthetics=["Traditional", "Minimalist", "Indo-Western"]),
    _g(key="kurta_aline", name="A-line kurta", category="traditional", region="indian",
       description="A tunic that widens gradually toward the hem.",
       silhouette="a_line", fit="semi_fitted", formality="smart_casual",
       occasions=["everyday", "work", "festival"], climates=["hot", "warm"],
       styling=["Skims the hip rather than sitting on it",
                "Pairs with narrow bottoms to keep the line clean"],
       suits_shapes=["pear", "apple"], aesthetics=["Traditional", "Contemporary"]),
    _g(key="salwar_suit", name="Salwar suit", category="traditional", region="indian",
       description="Kurta with gathered salwar trousers and a dupatta.",
       silhouette="relaxed", fit="relaxed", formality="smart_casual",
       occasions=["everyday", "work", "festival"], climates=["hot", "warm", "humid"],
       styling=["The most forgiving traditional set for a long day",
                "Cotton for heat, silk blends for occasions"],
       aesthetics=["Traditional", "Modest Fashion"]),
    _g(key="sharara", name="Sharara set", category="traditional", region="indian",
       description="A short kurta over wide trousers flaring from the knee.",
       silhouette="wide_leg", fit="fitted_top", formality="occasion",
       occasions=["wedding", "festival"], climates=["warm", "temperate"],
       styling=["The flare sits at the knee, which reads as height",
                "A shorter kurta keeps the trouser shape visible"],
       suits_shapes=["inverted_triangle", "rectangle", "hourglass"],
       aesthetics=["Traditional", "Contemporary"]),
    _g(key="gharara", name="Gharara set", category="traditional", region="indian",
       description="Fitted to the knee with a gathered joint, then full flare.",
       silhouette="fit_and_flare", fit="fitted_thigh", formality="occasion",
       occasions=["wedding", "festival"], climates=["temperate"],
       styling=["The gathered knee joint is the point of the garment — keep it visible",
                "Traditionally worn with a short kurta"],
       suits_shapes=["rectangle", "hourglass"], aesthetics=["Traditional", "Vintage"]),
    _g(key="indo_western", name="Indo-Western set", category="traditional", region="indian",
       description="Traditional fabrics and motifs cut to contemporary shapes.",
       silhouette="varied", fit="varied", formality="occasion",
       occasions=["party", "wedding", "festival", "evening"], climates=["any"],
       styling=["A cape over a lehenga, a dhoti-cut trouser, a jacket kurta",
                "Reads formal without the full traditional commitment"],
       aesthetics=["Indo-Western", "Contemporary"]),
    _g(key="sherwani", name="Sherwani", category="traditional", region="indian",
       description="A long, structured coat worn over fitted trousers.",
       silhouette="structured", fit="tailored", formality="occasion",
       occasions=["wedding"], climates=["temperate", "cold"],
       styling=["Length is the main decision: knee, mid-calf or longer",
                "A contrast stole adds colour without changing the coat"],
       aesthetics=["Traditional", "Formal"]),
    _g(key="nehru_jacket", name="Nehru jacket", category="jackets", region="indian",
       description="A short, collarless waistcoat-style jacket.",
       silhouette="structured", fit="tailored", formality="smart_casual",
       occasions=["festival", "wedding", "work"], climates=["temperate", "cold"],
       styling=["Over a kurta, or over a plain shirt for an Indo-Western read",
                "Adds structure at the shoulder"],
       suits_shapes=["rectangle", "pear"], aesthetics=["Indo-Western", "Classic"]),
    _g(key="dhoti_pants", name="Dhoti trousers", category="trousers", region="indian",
       description="Draped trousers gathered at the hip, tapering at the ankle.",
       silhouette="draped", fit="relaxed", formality="smart_casual",
       occasions=["festival", "party", "everyday"], climates=["hot", "humid", "warm"],
       styling=["Volume sits at the hip, so a fitted top keeps it balanced",
                "One of the coolest things to wear in real heat"],
       suits_shapes=["rectangle", "inverted_triangle"], aesthetics=["Indo-Western", "Contemporary"]),
    _g(key="palazzo", name="Palazzo trousers", category="trousers", region="both",
       description="Wide, fluid trousers falling straight from the waist.",
       silhouette="wide_leg", fit="relaxed", formality="smart_casual",
       occasions=["everyday", "work", "festival"], climates=["hot", "humid", "warm"],
       styling=["Full length keeps the line unbroken",
                "Works under a kurta and with a plain shirt equally"],
       suits_shapes=["pear", "inverted_triangle", "apple"],
       aesthetics=["Contemporary", "Indo-Western", "Modest Fashion"]),
]

# ------------------------------------------------------------- global fashion

GLOBAL: list[Garment] = [
    _g(key="tshirt", name="T-shirt", category="tops", region="global",
       description="A knit top, crew or V-neck.",
       silhouette="straight", fit="relaxed", formality="casual",
       occasions=["everyday"], climates=["any"],
       styling=["The neckline does most of the work — a V lengthens, a crew squares",
                "Tucking the front changes the waist line entirely"],
       aesthetics=["Casual", "Minimalist", "Streetwear"]),
    _g(key="button_shirt", name="Button-down shirt", category="shirts", region="global",
       description="A collared shirt with a full button placket.",
       silhouette="straight", fit="semi_fitted", formality="business",
       occasions=["work", "everyday", "formal"], climates=["temperate", "warm"],
       styling=["Open over a T-shirt it becomes a light layer",
                "A half-tuck defines the waist without looking formal"],
       suits_shapes=["rectangle", "pear"], aesthetics=["Classic", "Business Casual", "Preppy"]),
    _g(key="silk_blouse", name="Silk blouse", category="tops", region="global",
       description="A fluid top with a soft drape.",
       silhouette="fluid", fit="relaxed", formality="business",
       occasions=["work", "evening", "formal"], climates=["temperate", "warm"],
       styling=["Drapes rather than holds a shape",
                "Reads formal enough for work and soft enough for evening"],
       suits_shapes=["apple", "hourglass"], aesthetics=["Elegant", "Classic", "Business Casual"]),
    _g(key="wrap_top", name="Wrap top", category="tops", region="global",
       description="A top crossing at the front and tying at the waist.",
       silhouette="wrap", fit="adjustable", formality="smart_casual",
       occasions=["work", "everyday", "evening"], climates=["temperate", "warm"],
       styling=["The tie sets the waist wherever you want it",
                "The V-neck lengthens the neckline"],
       suits_shapes=["hourglass", "apple", "rectangle"], aesthetics=["Classic", "Romantic"]),
    _g(key="structured_top", name="Structured top", category="tops", region="global",
       description="A top with built-in shape at the shoulder or waist.",
       silhouette="structured", fit="fitted", formality="smart_casual",
       occasions=["work", "evening"], climates=["temperate"],
       styling=["Holds its own shape rather than following yours",
                "Shoulder structure balances a wider hip line"],
       suits_shapes=["pear", "rectangle"], aesthetics=["Contemporary", "Classic"]),
    _g(key="straight_jeans", name="Straight-leg jeans", category="jeans", region="global",
       description="A consistent width from hip to ankle.",
       silhouette="straight", fit="semi_fitted", formality="casual",
       occasions=["everyday", "college"], climates=["any"],
       styling=["The most versatile denim cut in this library",
                "Rise changes the look more than the leg does"],
       aesthetics=["Casual", "Classic", "Minimalist"]),
    _g(key="wide_jeans", name="Wide-leg jeans", category="jeans", region="global",
       description="Widening from the hip through the leg.",
       silhouette="wide_leg", fit="relaxed", formality="casual",
       occasions=["everyday", "college"], climates=["any"],
       styling=["Volume below balances width above",
                "Full length with a small heel keeps the line long"],
       suits_shapes=["inverted_triangle", "apple", "rectangle"],
       aesthetics=["Streetwear", "Contemporary", "Casual"]),
    _g(key="high_waist_trousers", name="High-waisted trousers", category="trousers", region="global",
       description="Tailored trousers sitting at the natural waist.",
       silhouette="straight", fit="tailored", formality="business",
       occasions=["work", "formal", "everyday"], climates=["temperate", "cold"],
       styling=["The waist line is where the leg appears to start",
                "Tucking anything into these lengthens the lower half"],
       suits_shapes=["pear", "rectangle", "hourglass"],
       aesthetics=["Business Casual", "Classic", "Minimalist"]),
    _g(key="wide_trousers", name="Wide-leg trousers", category="trousers", region="global",
       description="Tailored trousers with a full leg.",
       silhouette="wide_leg", fit="relaxed", formality="business",
       occasions=["work", "evening", "everyday"], climates=["warm", "temperate"],
       styling=["Fluid fabric keeps the volume soft rather than stiff",
                "A fitted top balances the volume"],
       suits_shapes=["pear", "inverted_triangle", "apple"],
       aesthetics=["Contemporary", "Minimalist", "Business Casual"]),
    _g(key="aline_skirt", name="A-line skirt", category="skirts", region="global",
       description="Narrow at the waist, widening toward the hem.",
       silhouette="a_line", fit="fitted_waist", formality="smart_casual",
       occasions=["work", "everyday", "evening"], climates=["warm", "temperate"],
       styling=["Skims the hip instead of following it",
                "Length changes formality more than the shape does"],
       suits_shapes=["pear", "apple", "inverted_triangle"],
       aesthetics=["Classic", "Preppy", "Romantic"]),
    _g(key="pleated_skirt", name="Pleated skirt", category="skirts", region="global",
       description="Folded panels falling from the waist.",
       silhouette="pleated", fit="fitted_waist", formality="smart_casual",
       occasions=["work", "everyday", "college"], climates=["temperate"],
       styling=["Pleats read as vertical lines while adding movement",
                "Midi length is the easiest to wear day to day"],
       suits_shapes=["rectangle", "pear"], aesthetics=["Preppy", "Classic", "Korean-Inspired"]),
    _g(key="pencil_skirt", name="Pencil skirt", category="skirts", region="global",
       description="Straight and close-fitting to the knee.",
       silhouette="straight", fit="fitted", formality="business",
       occasions=["work", "formal"], climates=["temperate"],
       styling=["Follows the line you already have",
                "A back vent decides how much you can stride"],
       suits_shapes=["hourglass", "rectangle"], aesthetics=["Classic", "Business Casual"]),
    _g(key="wrap_dress", name="Wrap dress", category="dresses", region="global",
       description="Crossing at the front and tying at the waist.",
       silhouette="wrap", fit="adjustable", formality="smart_casual",
       occasions=["work", "evening", "everyday"], climates=["warm", "temperate"],
       styling=["You set the waist and the neckline depth yourself",
                "One of the few dresses that fits across a size change"],
       suits_shapes=["hourglass", "apple", "pear"], aesthetics=["Classic", "Romantic", "Elegant"]),
    _g(key="shift_dress", name="Shift dress", category="dresses", region="global",
       description="Straight cut, hanging from the shoulders.",
       silhouette="straight", fit="relaxed", formality="smart_casual",
       occasions=["work", "everyday", "evening"], climates=["warm", "humid"],
       styling=["Skims the whole torso without touching the waist",
                "A belt adds definition when you want it, and comes off when you do not"],
       suits_shapes=["apple", "rectangle"], aesthetics=["Minimalist", "Classic", "Contemporary"]),
    _g(key="fit_flare_dress", name="Fit-and-flare dress", category="dresses", region="global",
       description="Fitted through the bodice, flaring from the waist.",
       silhouette="fit_and_flare", fit="fitted_bodice", formality="smart_casual",
       occasions=["evening", "party", "everyday"], climates=["warm", "temperate"],
       styling=["The flare point sets where the eye lands",
                "Works with both flat and heeled shoes"],
       suits_shapes=["pear", "hourglass", "rectangle"], aesthetics=["Romantic", "Classic", "Vintage"]),
    _g(key="slip_dress", name="Slip dress", category="dresses", region="global",
       description="A bias-cut dress on narrow straps.",
       silhouette="column", fit="fluid", formality="occasion",
       occasions=["evening", "party"], climates=["warm", "humid"],
       styling=["Bias cut follows the body closely",
                "Layers over a T-shirt for daytime"],
       suits_shapes=["rectangle", "hourglass"], aesthetics=["Minimalist", "Contemporary"]),
    _g(key="blazer_tailored", name="Tailored blazer", category="blazers", region="global",
       description="Structured shoulders, nipped through the body.",
       silhouette="structured", fit="tailored", formality="business",
       occasions=["work", "formal", "interview"], climates=["temperate", "cold"],
       styling=["Shoulder width is the single most alterable thing on it",
                "Worn open it reads as two vertical lines"],
       suits_shapes=["pear", "rectangle", "hourglass"],
       aesthetics=["Business Casual", "Classic", "Formal"]),
    _g(key="blazer_oversized", name="Oversized blazer", category="blazers", region="global",
       description="A dropped shoulder and a longer, looser body.",
       silhouette="relaxed", fit="oversized", formality="smart_casual",
       occasions=["everyday", "work", "evening"], climates=["temperate", "cold"],
       styling=["Sleeve length is what separates deliberate from borrowed",
                "Over a fitted base it keeps the proportion readable"],
       suits_shapes=["rectangle", "inverted_triangle"],
       aesthetics=["Streetwear", "Contemporary", "Minimalist"]),
    _g(key="cropped_jacket", name="Cropped jacket", category="jackets", region="global",
       description="Ending at or above the waist.",
       silhouette="cropped", fit="fitted", formality="smart_casual",
       occasions=["everyday", "evening"], climates=["temperate"],
       styling=["Ends at the narrowest point, which marks the waist",
                "Balances a fuller skirt or trouser"],
       suits_shapes=["pear", "hourglass"], aesthetics=["Vintage", "Contemporary", "Romantic"]),
    _g(key="longline_coat", name="Longline coat", category="outerwear", region="global",
       description="A straight coat falling below the knee.",
       silhouette="column", fit="relaxed", formality="business",
       occasions=["work", "everyday", "formal"], climates=["cold", "temperate"],
       styling=["One long vertical line over everything else",
                "Worn open it frames the outfit underneath"],
       suits_shapes=["apple", "rectangle", "inverted_triangle"],
       aesthetics=["Minimalist", "Classic", "Elegant"]),
    _g(key="denim_jacket", name="Denim jacket", category="jackets", region="global",
       description="A short, structured jacket in denim.",
       silhouette="cropped", fit="semi_fitted", formality="casual",
       occasions=["everyday", "college"], climates=["temperate", "warm"],
       styling=["Ends at the waist, so it marks it",
                "Over a kurta it reads Indo-Western rather than Western"],
       aesthetics=["Casual", "Streetwear", "Vintage"]),
    _g(key="trench", name="Trench coat", category="outerwear", region="global",
       description="A belted coat with a storm flap.",
       silhouette="structured", fit="adjustable", formality="business",
       occasions=["work", "everyday"], climates=["temperate", "cold"],
       styling=["Belted or open are two different outfits",
                "The most weather-useful formal layer here"],
       suits_shapes=["hourglass", "rectangle"], aesthetics=["Classic", "Elegant"]),
    _g(key="co_ord_set", name="Co-ord set", category="sets", region="both",
       description="Two matching pieces worn together.",
       silhouette="varied", fit="varied", formality="smart_casual",
       occasions=["everyday", "work", "party"], climates=["any"],
       styling=["Reads as one considered outfit with no decisions to make",
                "The pieces still work separately, which is most of the value"],
       aesthetics=["Contemporary", "Minimalist", "Korean-Inspired"]),
    _g(key="knit_set", name="Knit co-ord", category="sets", region="global",
       description="A matching knit top and bottom.",
       silhouette="relaxed", fit="relaxed", formality="casual",
       occasions=["everyday"], climates=["cold", "temperate"],
       styling=["Soft everywhere, so structure has to come from shoes or a coat"],
       aesthetics=["Athleisure", "Minimalist", "Korean-Inspired"]),
    _g(key="athleisure_set", name="Athleisure set", category="sets", region="global",
       description="Performance fabric cut for wearing beyond the gym.",
       silhouette="fitted", fit="fitted", formality="casual",
       occasions=["everyday", "vacation"], climates=["any"],
       styling=["A structured jacket over it moves it out of the gym",
                "Full-length leggings with a longer top if you prefer coverage"],
       aesthetics=["Athleisure", "Casual", "Streetwear"]),
    _g(key="modest_maxi", name="Maxi dress", category="dresses", region="both",
       description="Full length, loose through the body.",
       silhouette="column", fit="relaxed", formality="smart_casual",
       occasions=["everyday", "vacation", "festival"], climates=["hot", "humid", "warm"],
       styling=["Full coverage without a single layer of heat",
                "A belt or an open shirt over it changes the shape entirely"],
       aesthetics=["Modest Fashion", "Romantic", "Casual"]),
    _g(key="abaya_style", name="Abaya-style overlayer", category="outerwear", region="both",
       description="A long open or closed robe worn over other clothes.",
       silhouette="column", fit="relaxed", formality="smart_casual",
       occasions=["everyday", "formal", "festival"], climates=["hot", "warm", "temperate"],
       styling=["One long line, which is why it reads formal so easily",
                "Fabric weight decides whether it is a coat or a layer"],
       aesthetics=["Modest Fashion", "Minimalist", "Elegant"]),
    _g(key="loafers", name="Loafers", category="footwear", region="global",
       description="A flat slip-on shoe.",
       silhouette="flat", fit="standard", formality="business",
       occasions=["work", "everyday", "college"], climates=["any"],
       styling=["Formal enough for work and comfortable enough for a full day"],
       aesthetics=["Preppy", "Classic", "Business Casual"]),
    _g(key="juttis", name="Juttis / mojaris", category="footwear", region="indian",
       description="A flat embroidered slip-on.",
       silhouette="flat", fit="standard", formality="occasion",
       occasions=["festival", "wedding", "everyday"], climates=["any"],
       styling=["Traditional with a lehenga and unexpected with jeans, both deliberate"],
       aesthetics=["Traditional", "Indo-Western"]),
    _g(key="block_heels", name="Block heels", category="footwear", region="both",
       description="A heel with a wide, stable base.",
       silhouette="heeled", fit="standard", formality="smart_casual",
       occasions=["work", "wedding", "evening"], climates=["any"],
       styling=["Height without the balance cost of a stiletto",
                "Survives grass and uneven floors, which matters at weddings"],
       aesthetics=["Classic", "Contemporary"]),
    _g(key="white_sneakers", name="White sneakers", category="footwear", region="global",
       description="A clean, low-profile trainer.",
       silhouette="flat", fit="standard", formality="casual",
       occasions=["everyday", "college", "vacation"], climates=["any"],
       styling=["Reads intentional with almost anything, including a saree"],
       aesthetics=["Minimalist", "Streetwear", "Casual"]),
    _g(key="structured_bag", name="Structured bag", category="bags", region="global",
       description="A bag that holds its own shape.",
       silhouette="structured", fit="standard", formality="business",
       occasions=["work", "formal"], climates=["any"],
       styling=["Structure beside soft clothing is what reads as considered"],
       aesthetics=["Classic", "Business Casual", "Elegant"]),
    _g(key="potli", name="Potli bag", category="bags", region="indian",
       description="A drawstring pouch, often embroidered.",
       silhouette="soft", fit="standard", formality="occasion",
       occasions=["wedding", "festival"], climates=["any"],
       styling=["Holds very little, which is the point at a wedding"],
       aesthetics=["Traditional", "Indo-Western"]),
    _g(key="tote", name="Tote bag", category="bags", region="global",
       description="A large open-top carry bag.",
       silhouette="soft", fit="standard", formality="casual",
       occasions=["work", "everyday", "college"], climates=["any"],
       styling=["The only bag here that takes a laptop and a change of shoes"],
       aesthetics=["Minimalist", "Casual", "Business Casual"]),
    _g(key="dupatta", name="Dupatta", category="accessories", region="indian",
       description="A long scarf worn across the shoulders or over the head.",
       silhouette="draped", fit="adjustable", formality="occasion",
       occasions=["festival", "wedding", "everyday"], climates=["any"],
       styling=["How you drape it changes the outfit more than the fabric does",
                "A contrast dupatta is the cheapest way to restyle a set"],
       aesthetics=["Traditional", "Modest Fashion", "Indo-Western"]),
    _g(key="silk_scarf", name="Silk scarf", category="accessories", region="global",
       description="A small square or long scarf in silk.",
       silhouette="draped", fit="adjustable", formality="smart_casual",
       occasions=["work", "everyday"], climates=["any"],
       styling=["Brings your palette right up beside your face",
                "At the neck, on a bag, or tied through a belt loop"],
       aesthetics=["Classic", "Vintage", "Elegant"]),
    _g(key="belt", name="Waist belt", category="accessories", region="both",
       description="A belt worn at the natural waist.",
       silhouette="structured", fit="adjustable", formality="smart_casual",
       occasions=["work", "everyday", "festival"], climates=["any"],
       styling=["Adds a waist to anything straight, including a kurta or a coat"],
       suits_shapes=["rectangle", "apple"], aesthetics=["Classic", "Contemporary"]),
]

GARMENTS: list[Garment] = INDIAN + GLOBAL
GARMENT_BY_KEY = {g.key: g for g in GARMENTS}


def by_category(category: str) -> list[Garment]:
    return [g for g in GARMENTS if g.category == category]


def by_region(region: str) -> list[Garment]:
    if region == "both":
        return list(GARMENTS)
    return [g for g in GARMENTS if g.region in (region, "both")]
